name: Génération LilyPond

on:
  push:
    paths:
      - 'lilypond/*.ly'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Installer LilyPond
        run: |
          sudo apt update
          sudo apt install -y lilypond

      - name: Générer SVG et PDF
        run: |
          mkdir -p assets
          for file in lilypond/*.ly; do
            filename=$(basename "$file" .ly)
            lilypond -dbackend=svg -o assets/$filename "$file"
            lilypond -o assets/$filename "$file"
          done

      - name: Commit des fichiers générés
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add assets/*.svg assets/*.pdf
          git commit -m "Mise à jour automatique des partitions" || echo "Pas de changements"
          git push
